#!/bin/bash

# Fonction pour se connecter en SSH
connect_ssh() {
    echo "Connexion SSH en cours..."
    ssh $username@$hostname "echo Connexion SSH établie sur \`hostname\`"
    return $?
}

# Commande pour afficher les utilisateurs via SSH
show_users() {
    ssh $username@$hostname "awk -F: '\$3 >= 1000 && \$1 != \"nobody\" {print \$1}' /etc/passwd"
}

# Fonction pour éteindre le serveur via SSH
shutdown_server() {
    read -p "Êtes-vous sûr de vouloir éteindre le serveur ? (oui/non) : " confirmation
    if [ "$confirmation" = "oui" ]; then
        read -s -p "Entrez le mot de passe sudo pour $username@$hostname : " password
        echo ""
        echo "Extinction du serveur..."
        ssh $username@$hostname "echo '$password' | sudo -S shutdown now"
        
        # Vérifier si la connexion SSH est rompue
        ssh_exit_status=$?
        if [ $ssh_exit_status -ne 0 ]; then
            echo "Le serveur est en cours d'extinction."
            exit 0
        else
            echo "Échec de l'arrêt du serveur."
        fi
    else
        echo "Opération annulée."
    fi
}

# Fonction pour redémarrer le serveur via SSH
reboot_server() {
    read -p "Êtes-vous sûr de vouloir redémarrer le serveur ? (oui/non) : " confirmation
    if [ "$confirmation" = "oui" ]; then
        read -s -p "Entrez le mot de passe sudo pour $username@$hostname : " password
        echo ""
        echo "Redémarrage du serveur..."
        ssh $username@$hostname "echo '$password' | sudo -S reboot"
        if [ $? -eq 0 ]; then
            echo "Le serveur est en cours de redémarrage."
            exit 0
        else
            echo "Échec du redémarrage du serveur."
        fi
    else
        echo "Opération annulée."
    fi
}

# Fonction pour afficher le menu
show_menu() {
    echo ""
    echo "Menu :"
    echo "1. Éteindre le serveur"
    echo "2. Redémarrer le serveur"
    echo "3. Quitter"
}

# Demander les identifiants SSH
echo "Entrez les informations de connexion SSH :"
read -p "Nom d'utilisateur : " username
read -p "Adresse IP ou nom de domaine : " hostname

# Boucle pour la connexion SSH
while ! connect_ssh; do
    echo "Échec de la connexion SSH. Veuillez réessayer."
    read -p "Nom d'utilisateur : " username
    read -p "Adresse IP ou nom de domaine : " hostname
done

echo "Connexion établie avec succès!"

# Afficher le menu principal
while true; do
    show_menu

    read -p "Choisissez une option (1/2/3) : " choice
    case $choice in
        1)
            echo "Option 1 : Éteindre le serveur"
            shutdown_server
            ;;
        2)
            echo "Option 2 : Redémarrer le serveur"
            reboot_server
            ;;
        3)
            echo "Option 3 : Au revoir!"
            break
            ;;
        *)
            echo "Option invalide. Veuillez choisir une option valide."
            ;;
    esac
done
