#!/bin/bash

# Récupérer le nom de l'utilisateur
get_user_name() {
    echo "$(whoami)"
}

# Récupérer l'adresse IP
get_ip_address() {
    hostname -I | awk '{print $1}'
}

# Récupérer l'architecture du processeur
get_processor_architecture() {
    echo "$(uname -m)"
}

# Récupérer les informations sur le disque dur
get_disk_info() {
    df -h --output=source,target,fstype,size,used,avail,pcent | awk 'NR==1{next} {print "Device: "$1"\nMountpoint: "$2"\nFile system type: "$3"\nTotal Size: "$4"\nUsed: "$5"\nFree: "$6"\nPercentage Used: "$7"\n"}'
}

# Afficher les informations
echo "Nom de l'utilisateur: $(get_user_name)"
echo "Adresse IP: $(get_ip_address)"
echo "Architecture du processeur: $(get_processor_architecture)"
echo -e "\nInformations sur le disque dur:"
get_disk_info
